Repository docconneting/docconneting, pull requests merged in 2025-04, with the labels that each got.

#3 [#1] 기본 Entity, Repository 생성
  src/main/java/com/example/docconneting/common/enums/Major.java
  src/main/java/com/example/docconneting/domain/alarm/entity/.gitkeep
  src/main/java/com/example/docconneting/domain/alarm/entity/Alarm.java
  src/main/java/com/example/docconneting/domain/alarm/repository/.gitkeep
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/example/docconneting/domain/chatting/entity/.gitkeep
  src/main/java/com/example/docconneting/domain/chatting/entity/ChattingRoom.java
  src/main/java/com/example/docconneting/domain/chatting/entity/Message.java
  src/main/java/com/example/docconneting/domain/chatting/repository/.gitkeep
  src/main/java/com/example/docconneting/domain/chatting/repository/ChattingRoomRepository.java
  src/main/java/com/example/docconneting/domain/chatting/repository/MessageRepository.java
  src/main/java/com/example/docconneting/domain/comment/entity/.gitkeep
  src/main/java/com/example/docconneting/domain/comment/entity/Comment.java
  src/main/java/com/example/docconneting/domain/comment/repository/.gitkeep
  src/main/java/com/example/docconneting/domain/comment/repository/CommentRepository.java
  src/main/java/com/example/docconneting/domain/coupon/entity/.gitkeep
  src/main/java/com/example/docconneting/domain/coupon/entity/Coupon.java
  src/main/java/com/example/docconneting/domain/coupon/entity/CouponHistory.java
  src/main/java/com/example/docconneting/domain/coupon/entity/PatientCoupon.java
  src/main/java/com/example/docconneting/domain/coupon/repository/.gitkeep
  src/main/java/com/example/docconneting/domain/coupon/repository/CouponHistoryRepository.java
  src/main/java/com/example/docconneting/domain/coupon/repository/CouponRepository.java
  src/main/java/com/example/docconneting/domain/coupon/repository/PatientCouponRepository.java
  src/main/java/com/example/docconneting/domain/doctor/entity/.gitkeep
  src/main/java/com/example/docconneting/domain/doctor/repository/.gitkeep
  src/main/java/com/example/docconneting/domain/order/entity/.gitkeep
  src/main/java/com/example/docconneting/domain/order/entity/Order.java
  src/main/java/com/example/docconneting/domain/order/enums/OrderProduct.java
  src/main/java/com/example/docconneting/domain/order/enums/OrderType.java
  src/main/java/com/example/docconneting/domain/order/repository/.gitkeep
  src/main/java/com/example/docconneting/domain/order/repository/OrderRepository.java
  src/main/java/com/example/docconneting/domain/payment/entity/.gitkeep
  src/main/java/com/example/docconneting/domain/payment/entity/PaymentHistory.java
  src/main/java/com/example/docconneting/domain/payment/enums/PaymentStatus.java
  src/main/java/com/example/docconneting/domain/payment/repository/.gitkeep
  src/main/java/com/example/docconneting/domain/payment/repository/PaymentHistoryRepository.java
  src/main/java/com/example/docconneting/domain/point/entity/.gitkeep
  src/main/java/com/example/docconneting/domain/point/entity/PointHistory.java
  src/main/java/com/example/docconneting/domain/point/enums/PointType.java
  src/main/java/com/example/docconneting/domain/point/repository/.gitkeep
  src/main/java/com/example/docconneting/domain/point/repository/PointHistoryRepository.java
  src/main/java/com/example/docconneting/domain/post/entity/.gitkeep
  src/main/java/com/example/docconneting/domain/post/entity/Post.java
  src/main/java/com/example/docconneting/domain/post/repository/.gitkeep
  src/main/java/com/example/docconneting/domain/post/repository/PostRepository.java
  src/main/java/com/example/docconneting/domain/user/entity/.gitkeep
  src/main/java/com/example/docconneting/domain/user/entity/User.java
  src/main/java/com/example/docconneting/domain/user/enums/UserRole.java
  src/main/java/com/example/docconneting/domain/user/repository/.gitkeep
  src/main/java/com/example/docconneting/domain/user/repository/UserRepository.java
Labels: 기능

#13 [#5] 의사 단건조회, 다건조회 기능 생성
  build.gradle
  src/main/java/com/example/docconneting/common/config/.gitkeep
  src/main/java/com/example/docconneting/common/config/QuerydslConfig.java
  src/main/java/com/example/docconneting/common/enums/Major.java
  src/main/java/com/example/docconneting/common/exception/constant/ErrorCode.java
  src/main/java/com/example/docconneting/common/response/PageResult.java
  src/main/java/com/example/docconneting/domain/alarm/entity/Alarm.java
  src/main/java/com/example/docconneting/domain/chatting/entity/ChattingRoom.java
  src/main/java/com/example/docconneting/domain/chatting/entity/Message.java
  src/main/java/com/example/docconneting/domain/comment/entity/Comment.java
  src/main/java/com/example/docconneting/domain/coupon/entity/Coupon.java
  src/main/java/com/example/docconneting/domain/coupon/entity/CouponHistory.java
  src/main/java/com/example/docconneting/domain/coupon/entity/PatientCoupon.java
  src/main/java/com/example/docconneting/domain/doctor/controller/.gitkeep
  src/main/java/com/example/docconneting/domain/doctor/controller/DoctorController.java
  src/main/java/com/example/docconneting/domain/doctor/dto/.gitkeep
  src/main/java/com/example/docconneting/domain/doctor/dto/DoctorResponse.java
  src/main/java/com/example/docconneting/domain/doctor/service/.gitkeep
  src/main/java/com/example/docconneting/domain/doctor/service/DoctorService.java
  src/main/java/com/example/docconneting/domain/order/entity/Order.java
  src/main/java/com/example/docconneting/domain/payment/entity/PaymentHistory.java
  src/main/java/com/example/docconneting/domain/point/entity/PointHistory.java
  src/main/java/com/example/docconneting/domain/post/entity/Post.java
  src/main/java/com/example/docconneting/domain/user/entity/User.java
  src/main/java/com/example/docconneting/domain/user/repository/UserRepository.java
  src/main/java/com/example/docconneting/domain/user/repository/UserRepositoryQuery.java
  src/main/java/com/example/docconneting/domain/user/repository/UserRepositoryQueryImpl.java
  src/test/java/com/example/docconneting/domain/doctor/service/DoctorServiceTest.java
Labels: 기능, 테스트코드

#15 [#5] 의사 다건 조회 인덱싱 적용, 테스트 코드 리팩토링, 페이징 부분 누락 쿼리 추가
  src/main/java/com/example/docconneting/common/enums/Major.java
  src/main/java/com/example/docconneting/domain/doctor/controller/DoctorController.java
  src/main/java/com/example/docconneting/domain/doctor/dto/DoctorResponse.java
  src/main/java/com/example/docconneting/domain/doctor/service/DoctorService.java
  src/main/java/com/example/docconneting/domain/user/entity/User.java
  src/main/java/com/example/docconneting/domain/user/repository/UserRepositoryQueryImpl.java
  src/test/java/com/example/docconneting/domain/doctor/controller/DoctorControllerTest.java
  src/test/java/com/example/docconneting/domain/doctor/service/DoctorServiceTest.java
Labels: 테스트코드, 버그 수정

#17 [#5] Entity 및 DTO 생성자 정적 메서드로 변경
  src/main/java/com/example/docconneting/domain/doctor/dto/DoctorResponse.java
  src/main/java/com/example/docconneting/domain/doctor/service/DoctorService.java
  src/main/java/com/example/docconneting/domain/user/entity/User.java
  src/test/java/com/example/docconneting/domain/doctor/controller/DoctorControllerTest.java
  src/test/java/com/example/docconneting/domain/doctor/service/DoctorServiceTest.java
Labels: 리팩토링

#20 [#5] index명 수정
  src/main/java/com/example/docconneting/domain/user/entity/User.java
Labels: 리팩토링

#21 [#14] 회원가입, 로그인, 마이페이지 조회, 비밀번호 수정, 의사 이미지 수정, 토큰 재발급 기능 생성, pr 리뷰 기반 리팩토링
  build.gradle
  src/main/java/com/example/docconneting/common/config/FilterConfig.java
  src/main/java/com/example/docconneting/common/config/JwtUtil.java
  src/main/java/com/example/docconneting/common/config/PasswordEncoder.java
  src/main/java/com/example/docconneting/common/config/RedisConfig.java
  src/main/java/com/example/docconneting/common/config/WebConfig.java
  src/main/java/com/example/docconneting/common/exception/constant/ErrorCode.java
  src/main/java/com/example/docconneting/common/filter/JwtFilter.java
  src/main/java/com/example/docconneting/common/resolver/AuthUserArgumentResolver.java
  src/main/java/com/example/docconneting/domain/Auth/annotation/Auth.java
  src/main/java/com/example/docconneting/domain/Auth/controller/AuthController.java
  src/main/java/com/example/docconneting/domain/Auth/dto/request/UserRefreshTokenRequestDto.java
  src/main/java/com/example/docconneting/domain/Auth/dto/request/UserSignUpRequestDto.java
  src/main/java/com/example/docconneting/domain/Auth/dto/request/UserSigninRequestDto.java
  src/main/java/com/example/docconneting/domain/Auth/dto/response/UserRefreshTokenResponseDto.java
  src/main/java/com/example/docconneting/domain/Auth/dto/response/UserSignInResponseDto.java
  src/main/java/com/example/docconneting/domain/Auth/entity/AuthUser.java
  src/main/java/com/example/docconneting/domain/Auth/service/AuthService.java
  src/main/java/com/example/docconneting/domain/Auth/service/RefreshTokenService.java
  src/main/java/com/example/docconneting/domain/user/controller/UserController.java
  src/main/java/com/example/docconneting/domain/user/dto/request/UpdateImageRequestDto.java
  src/main/java/com/example/docconneting/domain/user/dto/request/UpdatePasswordRequestDto.java
  src/main/java/com/example/docconneting/domain/user/dto/response/UserMyPageResponseDto.java
  src/main/java/com/example/docconneting/domain/user/entity/User.java
  src/main/java/com/example/docconneting/domain/user/enums/UserRole.java
  src/main/java/com/example/docconneting/domain/user/repository/UserRepository.java
  src/main/java/com/example/docconneting/domain/user/service/UserService.java
  src/main/resources/application.yml
Labels: 리팩토링, 기능

#25 [#6], [#10] 포인트 조회, 테스트 코드 작성
  src/main/java/com/example/docconneting/domain/alarm/entity/Alarm.java
  src/main/java/com/example/docconneting/domain/chatting/entity/ChattingRoom.java
  src/main/java/com/example/docconneting/domain/chatting/entity/Message.java
  src/main/java/com/example/docconneting/domain/comment/entity/Comment.java
  src/main/java/com/example/docconneting/domain/coupon/entity/Coupon.java
  src/main/java/com/example/docconneting/domain/coupon/entity/CouponHistory.java
  src/main/java/com/example/docconneting/domain/coupon/entity/PatientCoupon.java
  src/main/java/com/example/docconneting/domain/order/entity/Order.java
  src/main/java/com/example/docconneting/domain/payment/entity/PaymentHistory.java
  src/main/java/com/example/docconneting/domain/point/controller/.gitkeep
  src/main/java/com/example/docconneting/domain/point/controller/PointController.java
  src/main/java/com/example/docconneting/domain/point/dto/.gitkeep
  src/main/java/com/example/docconneting/domain/point/dto/response/PointResponse.java
  src/main/java/com/example/docconneting/domain/point/entity/PointHistory.java
  src/main/java/com/example/docconneting/domain/point/service/.gitkeep
  src/main/java/com/example/docconneting/domain/point/service/PointService.java
  src/main/java/com/example/docconneting/domain/post/entity/Post.java
  src/main/java/com/example/docconneting/domain/user/repository/UserRepository.java
  src/test/java/com/example/docconneting/domain/point/controller/PointControllerTest.java
  src/test/java/com/example/docconneting/domain/point/service/PointServiceTest.java
Labels: 기능, 테스트코드

#27 [#5] 로그인 적용 및 페이징 객체 수정
  src/main/java/com/example/docconneting/common/filter/JwtFilter.java
  src/main/java/com/example/docconneting/domain/doctor/controller/DoctorController.java
  src/main/java/com/example/docconneting/domain/doctor/service/DoctorService.java
  src/test/java/com/example/docconneting/domain/doctor/controller/DoctorControllerTest.java
  src/test/java/com/example/docconneting/domain/doctor/service/DoctorServiceTest.java
Labels: 리팩토링

#23 [#14] 이메일 중복 확인 로직 추가, dto 이름 리네이밍, auth 패키지 이름 리네이밍, 마이페이지 조회 의사/환자 분기 생성
  src/main/java/com/example/docconneting/common/resolver/AuthUserArgumentResolver.java
  src/main/java/com/example/docconneting/domain/Auth/controller/AuthController.java
  src/main/java/com/example/docconneting/domain/Auth/dto/response/UserRefreshTokenResponseDto.java
  src/main/java/com/example/docconneting/domain/Auth/dto/response/UserSignInResponseDto.java
  src/main/java/com/example/docconneting/domain/auth/annotation/Auth.java
  src/main/java/com/example/docconneting/domain/auth/controller/AuthController.java
  src/main/java/com/example/docconneting/domain/auth/dto/request/UserRefreshTokenRequest.java
  src/main/java/com/example/docconneting/domain/auth/dto/request/UserSignUpRequest.java
  src/main/java/com/example/docconneting/domain/auth/dto/request/UserSigninRequest.java
  src/main/java/com/example/docconneting/domain/auth/dto/response/UserRefreshTokenResponse.java
  src/main/java/com/example/docconneting/domain/auth/dto/response/UserSignInResponse.java
  src/main/java/com/example/docconneting/domain/auth/entity/AuthUser.java
  src/main/java/com/example/docconneting/domain/auth/service/AuthService.java
  src/main/java/com/example/docconneting/domain/auth/service/RefreshTokenService.java
  src/main/java/com/example/docconneting/domain/user/controller/UserController.java
  src/main/java/com/example/docconneting/domain/user/dto/request/UpdateImageRequest.java
  src/main/java/com/example/docconneting/domain/user/dto/request/UpdatePasswordRequest.java
  src/main/java/com/example/docconneting/domain/user/dto/response/DoctorMyPageResponse.java
  src/main/java/com/example/docconneting/domain/user/dto/response/PatientMyPageResponse.java
  src/main/java/com/example/docconneting/domain/user/dto/response/UserMyPageResponse.java
  src/main/java/com/example/docconneting/domain/user/dto/response/UserMyPageResponseDto.java
  src/main/java/com/example/docconneting/domain/user/service/UserService.java
Labels: 리팩토링

#30 [#7], [#11] 답글 생성 및 수정 기능 구현, 테스트 코드 작성
  build.gradle
  src/main/java/com/example/docconneting/common/exception/constant/ErrorCode.java
  src/main/java/com/example/docconneting/domain/comment/controller/CommentController.java
  src/main/java/com/example/docconneting/domain/comment/dto/request/CommentRequest.java
  src/main/java/com/example/docconneting/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/example/docconneting/domain/comment/entity/Comment.java
  src/main/java/com/example/docconneting/domain/comment/service/CommentService.java
  src/main/java/com/example/docconneting/domain/point/controller/PointController.java
  src/main/java/com/example/docconneting/domain/post/controller/PostController.java
  src/main/java/com/example/docconneting/domain/post/service/PostService.java
  src/test/java/com/example/docconneting/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/example/docconneting/domain/comment/service/CommentServiceTest.java
  src/test/java/com/example/docconneting/domain/post/controller/PostControllerTest.java
  src/test/java/com/example/docconneting/domain/post/service/PostServiceTest.java
Labels: 기능, 테스트코드

#34 [#32] 채팅방 생성, 조회, 리스트 조회 기능 구현
  build.gradle
  src/main/java/com/example/docconneting/common/config/WebSocketConfig.java
  src/main/java/com/example/docconneting/common/exception/constant/ErrorCode.java
  src/main/java/com/example/docconneting/common/filter/JwtFilter.java
  src/main/java/com/example/docconneting/domain/chatting/controller/.gitkeep
  src/main/java/com/example/docconneting/domain/chatting/controller/ChattingRoomController.java
  src/main/java/com/example/docconneting/domain/chatting/dto/.gitkeep
  src/main/java/com/example/docconneting/domain/chatting/dto/ChattingRoomCreateResponse.java
  src/main/java/com/example/docconneting/domain/chatting/dto/ChattingRoomListResponse.java
  src/main/java/com/example/docconneting/domain/chatting/dto/ChattingRoomSingleResponse.java
  src/main/java/com/example/docconneting/domain/chatting/entity/ChattingRoom.java
  src/main/java/com/example/docconneting/domain/chatting/repository/ChattingRoomRepository.java
  src/main/java/com/example/docconneting/domain/chatting/service/.gitkeep
  src/main/java/com/example/docconneting/domain/chatting/service/ChattingRoomService.java
  src/main/java/com/example/docconneting/domain/user/repository/UserRepository.java
Labels: 리팩토링, 기능

#36 [ #14 ] 마이페이지 조회, 비밀번호 수정, 이미지 수정, 회원가입, 로그인, 토큰 재발급 테스트코드 작성
  src/main/java/com/example/docconneting/domain/auth/controller/AuthController.java
  src/main/java/com/example/docconneting/domain/auth/dto/request/UserSignInRequest.java
  src/main/java/com/example/docconneting/domain/auth/service/AuthService.java
  src/main/java/com/example/docconneting/domain/user/controller/.gitkeep
  src/main/java/com/example/docconneting/domain/user/dto/.gitkeep
  src/main/java/com/example/docconneting/domain/user/dto/response/UserMyPageResponse.java
  src/main/java/com/example/docconneting/domain/user/entity/User.java
  src/main/java/com/example/docconneting/domain/user/service/.gitkeep
  src/main/java/com/example/docconneting/domain/user/service/UserService.java
  src/test/java/com/example/docconneting/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/example/docconneting/domain/auth/service/AuthServiceTest.java
  src/test/java/com/example/docconneting/domain/user/controller/UserControllerTest.java
  src/test/java/com/example/docconneting/domain/user/service/UserServiceTest.java
Labels: 테스트코드

#37 [#31] 주문 생성, 조회, 리스트 조회 기능 구현
  src/main/java/com/example/docconneting/common/exception/constant/ErrorCode.java
  src/main/java/com/example/docconneting/domain/order/controller/.gitkeep
  src/main/java/com/example/docconneting/domain/order/controller/OrderController.java
  src/main/java/com/example/docconneting/domain/order/dto/.gitkeep
  src/main/java/com/example/docconneting/domain/order/dto/request/OrderRequest.java
  src/main/java/com/example/docconneting/domain/order/dto/response/OrderResponse.java
  src/main/java/com/example/docconneting/domain/order/entity/Order.java
  src/main/java/com/example/docconneting/domain/order/enums/OrderProduct.java
  src/main/java/com/example/docconneting/domain/order/enums/OrderStatus.java
  src/main/java/com/example/docconneting/domain/order/enums/OrderType.java
  src/main/java/com/example/docconneting/domain/order/repository/OrderRepository.java
  src/main/java/com/example/docconneting/domain/order/service/.gitkeep
  src/main/java/com/example/docconneting/domain/order/service/OrderService.java
  src/main/java/com/example/docconneting/domain/payment/entity/PaymentHistory.java
  src/main/java/com/example/docconneting/domain/payment/enums/PaymentMethod.java
  src/main/java/com/example/docconneting/domain/payment/enums/PaymentStatus.java
  src/main/java/com/example/docconneting/domain/payment/repository/PaymentHistoryRepository.java
  src/main/java/com/example/docconneting/domain/point/enums/PointType.java
Labels: 기능

#38 [#31] 주문 서비스, 컨트롤러 테스트 코드 작성
  src/main/java/com/example/docconneting/common/exception/constant/ErrorCode.java
  src/main/java/com/example/docconneting/domain/order/dto/request/OrderRequest.java
  src/main/java/com/example/docconneting/domain/order/enums/OrderProduct.java
  src/main/java/com/example/docconneting/domain/order/service/OrderService.java
  src/test/java/com/example/docconneting/domain/order/controller/OrderControllerTest.java
  src/test/java/com/example/docconneting/domain/order/service/OrderServiceTest.java
Labels: 리팩토링, 테스트코드

#41 [#35] 채팅 기능, 채팅 예외 처리, 메시지 db 저장 구현
  src/main/java/com/example/docconneting/common/config/WebSocketConfig.java
  src/main/java/com/example/docconneting/common/controller/GlobalExceptionHandler.java
  src/main/java/com/example/docconneting/common/exception/constant/ErrorCode.java
  src/main/java/com/example/docconneting/common/handler/CustomStompErrorHandler.java
  src/main/java/com/example/docconneting/common/interceptor/JwtChannelInterceptor.java
  src/main/java/com/example/docconneting/domain/chatting/controller/ChattingRoomController.java
  src/main/java/com/example/docconneting/domain/chatting/controller/MessageController.java
  src/main/java/com/example/docconneting/domain/chatting/dto/request/MessageRequest.java
  src/main/java/com/example/docconneting/domain/chatting/dto/response/ChattingRoomCreateResponse.java
  src/main/java/com/example/docconneting/domain/chatting/dto/response/ChattingRoomListResponse.java
  src/main/java/com/example/docconneting/domain/chatting/dto/response/ChattingRoomSingleResponse.java
  src/main/java/com/example/docconneting/domain/chatting/dto/response/MessageResponse.java
  src/main/java/com/example/docconneting/domain/chatting/entity/Message.java
  src/main/java/com/example/docconneting/domain/chatting/service/ChattingRoomService.java
  src/main/java/com/example/docconneting/domain/chatting/service/MessageService.java
  src/main/resources/static/connect.html
Labels: 기능

#40 [#14] 이미지를 S3에 저장하는 로직으로 리팩토링
  build.gradle
  src/main/java/com/example/docconneting/common/config/S3Config.java
  src/main/java/com/example/docconneting/domain/auth/controller/AuthController.java
  src/main/java/com/example/docconneting/domain/auth/dto/request/UserSignUpRequest.java
  src/main/java/com/example/docconneting/domain/auth/service/AuthService.java
  src/main/java/com/example/docconneting/domain/user/controller/UserController.java
  src/main/java/com/example/docconneting/domain/user/dto/request/UpdateImageRequest.java
  src/main/java/com/example/docconneting/domain/user/service/S3Service.java
  src/main/java/com/example/docconneting/domain/user/service/UserService.java
  src/test/java/com/example/docconneting/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/example/docconneting/domain/auth/service/AuthServiceTest.java
  src/test/java/com/example/docconneting/domain/user/controller/UserControllerTest.java
  src/test/java/com/example/docconneting/domain/user/service/UserServiceTest.java
Labels: 리팩토링, 테스트코드

#45 [#42] PostController, ChattingRoomController 일부 수정
  src/test/java/com/example/docconneting/domain/chatting/controller/ChattingRoomControllerTest.java
  src/test/java/com/example/docconneting/domain/post/controller/PostControllerTest.java
Labels: 테스트코드

#47 [#32], [#42] 채팅방 삭제 기능 구현, 테스트 코드 작성
  src/main/java/com/example/docconneting/domain/chatting/controller/ChattingRoomController.java
  src/main/java/com/example/docconneting/domain/chatting/service/ChattingRoomService.java
  src/test/java/com/example/docconneting/domain/chatting/controller/ChattingRoomControllerTest.java
  src/test/java/com/example/docconneting/domain/chatting/service/ChattingRoomServiceTest.java
Labels: 기능, 테스트코드

#50 엔티티 기본 생성자 변경
  src/main/java/com/example/docconneting/domain/alarm/entity/Alarm.java
  src/main/java/com/example/docconneting/domain/chatting/entity/ChattingRoom.java
  src/main/java/com/example/docconneting/domain/chatting/entity/Message.java
  src/main/java/com/example/docconneting/domain/comment/entity/Comment.java
  src/main/java/com/example/docconneting/domain/coupon/entity/Coupon.java
  src/main/java/com/example/docconneting/domain/coupon/entity/CouponHistory.java
  src/main/java/com/example/docconneting/domain/coupon/entity/PatientCoupon.java
  src/main/java/com/example/docconneting/domain/order/entity/Order.java
  src/main/java/com/example/docconneting/domain/payment/entity/PaymentHistory.java
  src/main/java/com/example/docconneting/domain/point/entity/PointHistory.java
  src/main/java/com/example/docconneting/domain/post/entity/Post.java
  src/main/java/com/example/docconneting/domain/user/entity/User.java
Labels: 리팩토링

#54 [#48] 채팅방 메시지 목록 조회 기능 구현
  src/main/java/com/example/docconneting/domain/chatting/controller/MessageController.java
  src/main/java/com/example/docconneting/domain/chatting/dto/response/MessageListResponse.java
  src/main/java/com/example/docconneting/domain/chatting/repository/MessageRepository.java
  src/main/java/com/example/docconneting/domain/chatting/service/MessageService.java
  src/test/java/com/example/docconneting/domain/chatting/controller/ChattingRoomControllerTest.java
  src/test/java/com/example/docconneting/domain/chatting/controller/MessageControllerTest.java
  src/test/java/com/example/docconneting/domain/chatting/service/ChattingRoomServiceTest.java
  src/test/java/com/example/docconneting/domain/chatting/service/MessageServiceTest.java
  src/test/java/com/example/docconneting/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/example/docconneting/domain/comment/service/CommentServiceTest.java
  src/test/java/com/example/docconneting/domain/point/service/PointServiceTest.java
  src/test/java/com/example/docconneting/domain/post/controller/PostControllerTest.java
  src/test/java/com/example/docconneting/domain/post/repository/PostRepositoryTest.java
  src/test/java/com/example/docconneting/domain/post/service/PostServiceTest.java
Labels: 리팩토링, 기능

#52 [#22] 알람 기능 구현
  .gitignore
  build.gradle
  src/main/java/com/example/docconneting/common/config/AsyncConfig.java
  src/main/java/com/example/docconneting/common/config/FcmInitializer.java
  src/main/java/com/example/docconneting/common/exception/constant/ErrorCode.java
  src/main/java/com/example/docconneting/common/exceptionhandler/CustomAsyncExceptionHandler.java
  src/main/java/com/example/docconneting/common/exceptionhandler/GlobalExceptionHandler.java
  src/main/java/com/example/docconneting/domain/alarm/controller/AlarmController.java
  src/main/java/com/example/docconneting/domain/alarm/dto/.gitkeep
  src/main/java/com/example/docconneting/domain/alarm/dto/AlarmResponse.java
  src/main/java/com/example/docconneting/domain/alarm/entity/AlarmHistories.java
  src/main/java/com/example/docconneting/domain/alarm/enums/AlarmType.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesBulkRepository.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesRepository.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesRepositoryQuery.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesRepositoryQueryImpl.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmRepository.java
  src/main/java/com/example/docconneting/domain/alarm/service/.gitkeep
  src/main/java/com/example/docconneting/domain/alarm/service/AlarmSenderService.java
  src/main/java/com/example/docconneting/domain/alarm/service/AlarmService.java
  src/main/java/com/example/docconneting/domain/auth/controller/AuthController.java
  src/main/java/com/example/docconneting/domain/auth/dto/request/UserSignInRequest.java
  src/main/java/com/example/docconneting/domain/comment/service/CommentService.java
  src/main/java/com/example/docconneting/domain/doctor/dto/DoctorResponse.java
  src/main/java/com/example/docconneting/domain/user/entity/User.java
  src/main/java/com/example/docconneting/domain/user/repository/UserRepository.java
  src/main/java/com/example/docconneting/domain/user/repository/UserRepositoryQuery.java
  src/main/java/com/example/docconneting/domain/user/repository/UserRepositoryQueryImpl.java
  src/main/resources/firebase/.gitkeep
  src/test/java/com/example/docconneting/domain/alarm/controller/AlarmControllerTest.java
  src/test/java/com/example/docconneting/domain/alarm/service/AlarmServiceTest.java
Labels: 기능, 테스트코드

#55 [#14] any() 대신 실제 데이터 삽입으로 리팩토링
  src/test/java/com/example/docconneting/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/example/docconneting/domain/auth/service/AuthServiceTest.java
  src/test/java/com/example/docconneting/domain/user/controller/UserControllerTest.java
Labels: 리팩토링, 테스트코드

#46 [#12] 쿠폰 생성, 발급, 조회, 사용 기능 추가
  build.gradle
  src/main/java/com/example/docconneting/common/exception/constant/ErrorCode.java
  src/main/java/com/example/docconneting/domain/coupon/controller/AdminCouponController.java
  src/main/java/com/example/docconneting/domain/coupon/controller/PatientCouponController.java
  src/main/java/com/example/docconneting/domain/coupon/dto/.gitkeep
  src/main/java/com/example/docconneting/domain/coupon/dto/request/CreateCouponRequest.java
  src/main/java/com/example/docconneting/domain/coupon/dto/response/CreateCouponResponse.java
  src/main/java/com/example/docconneting/domain/coupon/dto/response/IssueCouponResponse.java
  src/main/java/com/example/docconneting/domain/coupon/dto/response/PatientCouponResponse.java
  src/main/java/com/example/docconneting/domain/coupon/entity/Coupon.java
  src/main/java/com/example/docconneting/domain/coupon/entity/CouponHistory.java
  src/main/java/com/example/docconneting/domain/coupon/entity/PatientCoupon.java
  src/main/java/com/example/docconneting/domain/coupon/lock/DistributedLockManager.java
  src/main/java/com/example/docconneting/domain/coupon/lock/RedissonDistributedLockManager.java
  src/main/java/com/example/docconneting/domain/coupon/repository/PatientCouponRepository.java
  src/main/java/com/example/docconneting/domain/coupon/service/.gitkeep
  src/main/java/com/example/docconneting/domain/coupon/service/CouponService.java
  src/main/java/com/example/docconneting/domain/coupon/service/DistributedCouponService.java
  src/main/java/com/example/docconneting/domain/coupon/service/PatientCouponService.java
  src/test/java/com/example/docconneting/domain/coupon/service/CouponServiceTest.java
  src/test/java/com/example/docconneting/domain/coupon/service/PatientCouponServiceTest.java
Labels: 기능, 테스트코드

#49 [#39] 결제 기능 구현
  build.gradle
  src/main/java/com/example/docconneting/DocconnetingApplication.java
  src/main/java/com/example/docconneting/common/config/FilterConfig.java
  src/main/java/com/example/docconneting/common/config/PortOneProperties.java
  src/main/java/com/example/docconneting/common/exception/constant/ErrorCode.java
  src/main/java/com/example/docconneting/common/filter/JwtFilter.java
  src/main/java/com/example/docconneting/domain/order/controller/OrderController.java
  src/main/java/com/example/docconneting/domain/order/dto/request/OrderRequest.java
  src/main/java/com/example/docconneting/domain/order/dto/response/OrderResponse.java
  src/main/java/com/example/docconneting/domain/order/entity/Order.java
  src/main/java/com/example/docconneting/domain/order/enums/OrderStatus.java
  src/main/java/com/example/docconneting/domain/order/repository/OrderRepository.java
  src/main/java/com/example/docconneting/domain/order/service/OrderService.java
  src/main/java/com/example/docconneting/domain/payment/controller/.gitkeep
  src/main/java/com/example/docconneting/domain/payment/controller/PaymentController.java
  src/main/java/com/example/docconneting/domain/payment/dto/.gitkeep
  src/main/java/com/example/docconneting/domain/payment/dto/request/PaymentVerificationRequest.java
  src/main/java/com/example/docconneting/domain/payment/dto/request/PaymentWebhookRequest.java
  src/main/java/com/example/docconneting/domain/payment/dto/response/PortOnePaymentResponse.java
  src/main/java/com/example/docconneting/domain/payment/entity/PaymentHistory.java
  src/main/java/com/example/docconneting/domain/payment/enums/PaymentMethod.java
  src/main/java/com/example/docconneting/domain/payment/enums/PaymentStatus.java
  src/main/java/com/example/docconneting/domain/payment/repository/PaymentHistoryRepository.java
  src/main/java/com/example/docconneting/domain/payment/service/.gitkeep
  src/main/java/com/example/docconneting/domain/payment/service/PaymentApplicationService.java
  src/main/java/com/example/docconneting/domain/payment/service/PaymentService.java
  src/main/java/com/example/docconneting/domain/payment/service/PortOneService.java
  src/main/resources/firebase/.gitkeep
  src/test/java/com/example/docconneting/domain/order/controller/OrderControllerTest.java
  src/test/java/com/example/docconneting/domain/order/service/OrderServiceTest.java
Labels: 리팩토링, 기능

#61 [#53] Git action을 통한 자동 CICD
  .github/workflows/deploy.yml
  .github/workflows/test-pr.yml
  .gitignore
  build.gradle
  src/main/java/com/example/docconneting/common/config/RedisConfig.java
  src/main/java/com/example/docconneting/common/filter/JwtFilter.java
  src/main/java/com/example/docconneting/domain/health/HealthController.java
  src/test/java/com/example/docconneting/domain/order/controller/OrderControllerTest.java
  src/test/java/com/example/docconneting/domain/order/service/OrderServiceTest.java
Labels: 기능

#57 [#39] 주문 및 결제 테스트 코드 작성
  src/main/java/com/example/docconneting/common/exception/constant/ErrorCode.java
  src/main/java/com/example/docconneting/domain/order/dto/response/OrderResponse.java
  src/main/java/com/example/docconneting/domain/payment/controller/PaymentController.java
  src/main/java/com/example/docconneting/domain/payment/dto/request/PaymentWebhookRequest.java
  src/main/java/com/example/docconneting/domain/payment/service/PaymentApplicationService.java
  src/main/java/com/example/docconneting/domain/payment/service/PaymentService.java
  src/test/java/com/example/docconneting/domain/order/controller/OrderControllerTest.java
  src/test/java/com/example/docconneting/domain/order/service/OrderServiceTest.java
  src/test/java/com/example/docconneting/domain/payment/controller/PaymentControllerTest.java
  src/test/java/com/example/docconneting/domain/payment/service/PaymentApplicationServiceTest.java
  src/test/java/com/example/docconneting/domain/payment/service/PaymentServiceTest.java
Labels: 테스트코드

#66 [#53] AWS OpenSearch 연동
  build.gradle
  src/main/java/com/example/docconneting/DocconnetingApplication.java
  src/main/java/com/example/docconneting/common/OpenSearch/controller/OpenSearchController.java
  src/main/java/com/example/docconneting/common/OpenSearch/entity/IndexData.java
  src/main/java/com/example/docconneting/common/OpenSearch/service/OpenSearchService.java
  src/main/java/com/example/docconneting/common/config/OpenSearchConfig.java
  src/main/java/com/example/docconneting/common/filter/JwtFilter.java
Labels: 기능

#67 [#53] private 생성자, of 메서드 구현, 깃 액션에서 opensearch 관련 환경변수 선언 추가
  .github/workflows/deploy.yml
  .gitignore
  src/main/java/com/example/docconneting/common/OpenSearch/dto/UpdateDto.java
  src/main/java/com/example/docconneting/common/OpenSearch/entity/IndexData.java
  src/main/java/com/example/docconneting/common/OpenSearch/service/OpenSearchService.java
Labels: 버그 수정

#63 [#62] verifyAndCreateOrder() 분산 락 동작 검증 테스트
  build.gradle
  src/main/java/com/example/docconneting/common/config/AsyncConfig.java
  src/main/java/com/example/docconneting/common/config/annotation/DistributedLock.java
  src/main/java/com/example/docconneting/common/config/aop/AopForTransaction.java
  src/main/java/com/example/docconneting/common/config/aop/DistributedLockAop.java
  src/main/java/com/example/docconneting/common/config/parser/CustomSpringELParser.java
  src/main/java/com/example/docconneting/domain/order/repository/OrderRepository.java
  src/main/java/com/example/docconneting/domain/order/service/ChattingRoomAsyncService.java
  src/main/java/com/example/docconneting/domain/payment/enums/PaymentMethod.java
  src/main/java/com/example/docconneting/domain/payment/service/PaymentApplicationService.java
  src/test/java/com/example/docconneting/domain/order/service/ChattingRoomAsyncServiceTest.java
  src/test/java/com/example/docconneting/domain/payment/service/VerifyAndCreateOrderDistributedLockTest.java
Labels: 기능, 테스트코드

#59 [#58] 게시글 등록 동시성 문제 분산락 적용
  src/main/java/com/example/docconneting/common/parser/CustomSpringELParser.java
  src/main/java/com/example/docconneting/domain/coupon/service/PatientCouponService.java
  src/main/java/com/example/docconneting/domain/point/service/PointRefundService.java
  src/main/java/com/example/docconneting/domain/point/service/PointService.java
  src/main/java/com/example/docconneting/domain/post/service/PostService.java
  src/main/java/com/example/docconneting/domain/user/repository/UserRepository.java
  src/test/java/com/example/docconneting/domain/point/service/CreatePostDistributedLockTest.java
  src/test/java/com/example/docconneting/domain/point/service/PointServiceTest.java
  src/test/java/com/example/docconneting/domain/post/service/PostServiceTest.java
  src/test/java/com/example/docconneting/domain/user/repostiory/PessimisticLockWithPointTest.java
Labels: 리팩토링, 테스트코드

#71 [#53] test-pr 수정
  .github/workflows/test-pr.yml
  .gitignore
  build.gradle
  src/main/java/com/example/docconneting/common/config/RedissonConfig.java
  src/test/java/com/example/docconneting/DocconnetingApplicationTests.java
  src/test/java/com/example/docconneting/domain/alarm/controller/AlarmControllerTest.java
  src/test/java/com/example/docconneting/domain/alarm/service/AlarmServiceTest.java
  src/test/java/com/example/docconneting/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/example/docconneting/domain/auth/service/AuthServiceTest.java
  src/test/java/com/example/docconneting/domain/chatting/controller/ChattingRoomControllerTest.java
  src/test/java/com/example/docconneting/domain/chatting/controller/MessageControllerTest.java
  src/test/java/com/example/docconneting/domain/chatting/service/ChattingRoomServiceTest.java
  src/test/java/com/example/docconneting/domain/chatting/service/MessageServiceTest.java
  src/test/java/com/example/docconneting/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/example/docconneting/domain/comment/service/CommentServiceTest.java
  src/test/java/com/example/docconneting/domain/coupon/service/PatientCouponServiceTest.java
  src/test/java/com/example/docconneting/domain/doctor/controller/DoctorControllerTest.java
  src/test/java/com/example/docconneting/domain/doctor/service/DoctorServiceTest.java
  src/test/java/com/example/docconneting/domain/order/controller/OrderControllerTest.java
  src/test/java/com/example/docconneting/domain/order/service/OrderServiceTest.java
  src/test/java/com/example/docconneting/domain/payment/controller/PaymentControllerTest.java
  src/test/java/com/example/docconneting/domain/payment/service/PaymentApplicationServiceTest.java
  src/test/java/com/example/docconneting/domain/payment/service/PaymentServiceTest.java
  src/test/java/com/example/docconneting/domain/payment/service/VerifyAndCreateOrderDistributedLockTest.java
  src/test/java/com/example/docconneting/domain/point/controller/PointControllerTest.java
  src/test/java/com/example/docconneting/domain/point/service/CreatePostDistributedLockTest.java
  src/test/java/com/example/docconneting/domain/point/service/PointServiceTest.java
  src/test/java/com/example/docconneting/domain/post/controller/PostControllerTest.java
  src/test/java/com/example/docconneting/domain/post/service/FindExpiredPostServiceTest.java
  src/test/java/com/example/docconneting/domain/post/service/PostServiceTest.java
  src/test/java/com/example/docconneting/domain/post/service/RefundExpiredPostServiceTest.java
  src/test/java/com/example/docconneting/domain/user/controller/UserControllerTest.java
  src/test/java/com/example/docconneting/domain/user/service/UserServiceTest.java
Labels: 리팩토링

#72 [#68] 주문 채팅방 생성 비동기 처리
  src/main/java/com/example/docconneting/domain/order/service/ChattingRoomAsyncService.java
  src/main/java/com/example/docconneting/domain/payment/enums/PaymentMethod.java
  src/main/java/com/example/docconneting/domain/payment/service/PaymentApplicationService.java
  src/test/java/com/example/docconneting/common/config/TestAsyncConfig.java
  src/test/java/com/example/docconneting/domain/payment/service/PaymentApplicationServiceTest.java
  src/test/java/com/example/docconneting/domain/payment/service/VerifyAndCreateOrderDistributedLockTest.java
Labels: 기능, 테스트코드

#74 [#58] PointServiceTest 코드 수정
  src/test/java/com/example/docconneting/domain/coupon/service/OptimisticLockServiceTest.java
  src/test/java/com/example/docconneting/domain/point/service/PointServiceTest.java
Labels: 테스트코드, 버그 수정

#77 [#76 #53] Errorcode에 code 추가
  build.gradle
  src/main/java/com/example/docconneting/common/OpenSearch/controller/OpenSearchController.java
  src/main/java/com/example/docconneting/common/OpenSearch/dto/UpdateDto.java
  src/main/java/com/example/docconneting/common/OpenSearch/entity/IndexData.java
  src/main/java/com/example/docconneting/common/OpenSearch/service/OpenSearchService.java
  src/main/java/com/example/docconneting/common/config/OpenSearchConfig.java
  src/main/java/com/example/docconneting/common/exception/constant/ErrorCode.java
Labels: 리팩토링

#65 [#64] 메인 서버에서 알람 서버 분리 및 RabbitMQ 적용
  build.gradle
  src/main/java/com/example/docconneting/DocconnetingApplication.java
  src/main/java/com/example/docconneting/common/config/AsyncConfig.java
  src/main/java/com/example/docconneting/common/config/FcmInitializer.java
  src/main/java/com/example/docconneting/common/config/RabbitMQConfig.java
  src/main/java/com/example/docconneting/common/exceptionhandler/CustomAsyncExceptionHandler.java
  src/main/java/com/example/docconneting/common/principal/StompPrincipal.java
  src/main/java/com/example/docconneting/domain/alarm/controller/AlarmController.java
  src/main/java/com/example/docconneting/domain/alarm/dto/AlarmResponse.java
  src/main/java/com/example/docconneting/domain/alarm/entity/AlarmHistories.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesBulkRepository.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesRepository.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesRepositoryQuery.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesRepositoryQueryImpl.java
  src/main/java/com/example/docconneting/domain/alarm/service/AlarmSenderService.java
  src/main/java/com/example/docconneting/domain/alarm/service/AlarmService.java
  src/main/java/com/example/docconneting/domain/auth/controller/AuthController.java
  src/main/java/com/example/docconneting/domain/auth/service/AuthService.java
  src/main/java/com/example/docconneting/domain/comment/service/CommentService.java
  src/main/java/com/example/docconneting/domain/payment/service/PaymentApplicationService.java
  src/main/java/com/example/docconneting/domain/post/service/PostService.java
  src/main/java/com/example/docconneting/infra/rabbitmq/dto/FcmInfo.java
  src/main/java/com/example/docconneting/infra/rabbitmq/dto/Message.java
  src/main/java/com/example/docconneting/infra/rabbitmq/producer/AlarmServerSender.java
  src/test/java/com/example/docconneting/domain/alarm/controller/AlarmControllerTest.java
  src/test/java/com/example/docconneting/domain/alarm/service/AlarmServiceTest.java
  src/test/java/com/example/docconneting/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/example/docconneting/domain/comment/service/CommentServiceTest.java
  src/test/java/com/example/docconneting/domain/coupon/service/PatientCouponServiceTest.java
  src/test/java/com/example/docconneting/domain/payment/service/VerifyAndCreateOrderDistributedLockTest.java
  src/test/java/com/example/docconneting/domain/post/service/PostServiceTest.java
Labels: 리팩토링, 기능
