Repository docconneting/docconneting, pull requests merged in 2025-05, with the labels that each got.

#81 [#79] 유료 게시글에 ELK stack 적용
  build.gradle
  logstash.conf
  src/main/java/com/example/docconneting/domain/coupon/service/PatientCouponService.java
  src/main/java/com/example/docconneting/domain/point/service/PointService.java
  src/main/resources/logback.xml
  src/test/java/com/example/docconneting/domain/point/service/PointServiceTest.java
Labels: 기능

#84 [#78] ES 사용하여 키워드 검색 구현
  build.gradle
  src/main/java/com/example/docconneting/DocconnetingApplication.java
  src/main/java/com/example/docconneting/common/config/ElasticsearchConfig.java
  src/main/java/com/example/docconneting/common/config/RabbitMQConfig.java
  src/main/java/com/example/docconneting/domain/chatting/consumer/RabbitMQConsumerService.java
  src/main/java/com/example/docconneting/domain/chatting/controller/MessageController.java
  src/main/java/com/example/docconneting/domain/chatting/dto/response/ElasticsearchMessageListResponse.java
  src/main/java/com/example/docconneting/domain/chatting/dto/response/MessageSearchListResponse.java
  src/main/java/com/example/docconneting/domain/chatting/entity/ElasticsearchMessage.java
  src/main/java/com/example/docconneting/domain/chatting/repository/ElasticsearchMessageRepository.java
  src/main/java/com/example/docconneting/domain/chatting/repository/MessageRepository.java
  src/main/java/com/example/docconneting/domain/chatting/service/ElasticsearchMessageService.java
  src/main/java/com/example/docconneting/domain/chatting/service/MessageService.java
  src/test/java/com/example/docconneting/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/example/docconneting/domain/chatting/controller/ChattingRoomControllerTest.java
  src/test/java/com/example/docconneting/domain/chatting/controller/MessageControllerTest.java
  src/test/java/com/example/docconneting/domain/chatting/service/MessageServiceTest.java
  src/test/java/com/example/docconneting/domain/comment/controller/CommentControllerTest.java
  src/test/java/com/example/docconneting/domain/coupon/controller/AdminCouponControllerTest.java
  src/test/java/com/example/docconneting/domain/coupon/controller/PatientCouponControllerTest.java
  src/test/java/com/example/docconneting/domain/doctor/controller/DoctorControllerTest.java
  src/test/java/com/example/docconneting/domain/post/controller/PostControllerTest.java
  src/test/java/com/example/docconneting/domain/user/controller/UserControllerTest.java
Labels: 리팩토링, 기능, 테스트코드

#88 [#53] CI/CD 구현
  .github/workflows/deploy.yml
  .gitignore
  Dockerfile
  src/main/java/com/example/docconneting/common/config/ElasticsearchConfig.java
  src/main/java/com/example/docconneting/common/config/RabbitMQConfig.java
  src/main/java/com/example/docconneting/common/config/RedissonConfig.java
  src/main/java/com/example/docconneting/common/exception/constant/ErrorCode.java
  src/main/resources/logback-spring.xml
  src/main/resources/logback.xml
Labels: 기능

#98 [#97] 알람 서버 분리 복구
  build.gradle
  src/main/java/com/example/docconneting/common/config/AsyncConfig.java
  src/main/java/com/example/docconneting/common/config/FcmInitializer.java
  src/main/java/com/example/docconneting/common/exceptionhandler/CustomAsyncExceptionHandler.java
  src/main/java/com/example/docconneting/domain/alarm/controller/AlarmController.java
  src/main/java/com/example/docconneting/domain/alarm/dto/AlarmResponse.java
  src/main/java/com/example/docconneting/domain/alarm/entity/AlarmHistories.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesBulkRepository.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesRepository.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesRepositoryQuery.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesRepositoryQueryImpl.java
  src/main/java/com/example/docconneting/domain/alarm/service/AlarmSenderService.java
  src/main/java/com/example/docconneting/domain/alarm/service/AlarmService.java
  src/main/java/com/example/docconneting/domain/comment/service/CommentService.java
  src/main/java/com/example/docconneting/domain/payment/service/PaymentApplicationService.java
  src/main/java/com/example/docconneting/domain/post/service/PostService.java
  src/test/java/com/example/docconneting/domain/alarm/controller/AlarmControllerTest.java
  src/test/java/com/example/docconneting/domain/alarm/service/AlarmServiceTest.java
  src/test/java/com/example/docconneting/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/example/docconneting/domain/comment/service/CommentServiceTest.java
  src/test/java/com/example/docconneting/domain/payment/service/VerifyAndCreateOrderDistributedLockTest.java
  src/test/java/com/example/docconneting/domain/post/service/PostServiceTest.java
Labels: 리팩토링

#100 [#99] 알람 재시도 로직 추가
  .gitignore
  build.gradle
  src/main/java/com/example/docconneting/DocconnetingApplication.java
  src/main/java/com/example/docconneting/common/config/AsyncConfig.java
  src/main/java/com/example/docconneting/common/config/FcmInitializer.java
  src/main/java/com/example/docconneting/common/exception/constant/ErrorCode.java
  src/main/java/com/example/docconneting/common/exceptionhandler/CustomAsyncExceptionHandler.java
  src/main/java/com/example/docconneting/domain/alarm/controller/AlarmController.java
  src/main/java/com/example/docconneting/domain/alarm/dto/AlarmResponse.java
  src/main/java/com/example/docconneting/domain/alarm/entity/AlarmHistories.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesBulkRepository.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesRepository.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesRepositoryQuery.java
  src/main/java/com/example/docconneting/domain/alarm/repository/AlarmHistoriesRepositoryQueryImpl.java
  src/main/java/com/example/docconneting/domain/alarm/service/AlarmSenderService.java
  src/main/java/com/example/docconneting/domain/alarm/service/AlarmService.java
  src/main/java/com/example/docconneting/domain/alarm/service/FcmTokenService.java
  src/main/java/com/example/docconneting/domain/comment/service/CommentService.java
  src/main/java/com/example/docconneting/domain/payment/service/PaymentApplicationService.java
  src/main/java/com/example/docconneting/domain/post/service/PostService.java
  src/main/java/com/example/docconneting/domain/user/entity/User.java
  src/main/java/com/example/docconneting/domain/user/repository/UserRepository.java
  src/main/resources/firebase/.gitkeep
  src/test/java/com/example/docconneting/domain/alarm/controller/AlarmControllerTest.java
  src/test/java/com/example/docconneting/domain/alarm/service/AlarmServiceTest.java
  src/test/java/com/example/docconneting/domain/auth/controller/AuthControllerTest.java
  src/test/java/com/example/docconneting/domain/comment/service/CommentServiceTest.java
  src/test/java/com/example/docconneting/domain/payment/service/VerifyAndCreateOrderDistributedLockTest.java
  src/test/java/com/example/docconneting/domain/post/service/PostServiceTest.java
Labels: 리팩토링, 기능

#101 [#99][#5] 스레드 갯수 조절 및 누락된 인덱스 추가
  src/main/java/com/example/docconneting/common/config/AsyncConfig.java
  src/main/java/com/example/docconneting/domain/user/entity/User.java
Labels: 리팩토링
